version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD : root
    ports:
      - "3307:3307"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - "8182:84"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root